# 1. References

Title: Multi-Label Text Classification Using Scikit-multilearn: a Case Study with StackOverflow Questions

Link: https://medium.com/towards-artificial-intelligence/multi-label-text-classification-using-scikit-multilearn-case-study-with-stackoverflow-questions-768cb487ad12

In [1]:
import pandas as pd

In [2]:
DATA_DIR = "../../data/raw/"
# INPUT_FILE_NAME = 'cleaned.parquet'
INPUT_FILE_NAME = 'cleaned_squashed.parquet'


In [3]:
df = pd.read_parquet(DATA_DIR + INPUT_FILE_NAME)
# df = df[:200]  # same as df.head(10)
df.head()

speaker                              headline  \
0       Al Gore           Averting the climate crisis   
1     Amy Smith         Simple designs to save a life   
2  Ashraf Ghani         How to rebuild a broken state   
3    Burt Rutan  The real future of space exploration   
4  Chris Bangle              Great cars are great art   

                                         description duration  \
0  With the same humor and humanity he exuded in ...  0:16:17   
1  Fumes from indoor cooking fires kill more than...  0:15:06   
2  Ashraf Ghani's passionate and powerful 10-minu...  0:18:45   
3  In this passionate talk, legendary spacecraft ...  0:19:37   
4  American designer Chris Bangle explains his ph...  0:20:04   

                                                tags  \
0  cars,alternative energy,culture,politics,scien...   
1  MacArthur grant,simplicity,industrial design,a...   
2  corruption,poverty,economics,investment,milita...   
3  aircraft,flight,industrial design,NASA,rocket ...   
4  cars,industrial design,transportation,inventio...   

                                          transcript      WC  \
0  0:14\r\r\rThank you so much, Chris.\rAnd it's ...  2281.0   
1  0:11\r\r\rIn terms of invention,\rI'd like to ...  2687.0   
2  0:12\r\r\rA public, Dewey long ago observed,\r...  2506.0   
3  0:11\r\r\rI want to start off by saying, Houst...  3092.0   
4  0:12\r\r\rWhat I want to talk about is, as bac...  3781.0   

                                    clean_transcript  \
0  [thank, chris, truly, great, honor, opportunit...   
1  [term, invention, like, tell, tale, favorite, ...   
2  [public, dewey, long, ago, observe, constitute...   
3  [want, start, say, houston, problem, enter, se...   
4  [want, talk, background, idea, car, art, actua...   

                             clean_transcript_string  \
0  thank chris truly great honor opportunity come...   
1  term invention like tell tale favorite project...   
2  public dewey long ago observe constitute discu...   
3  want start say houston problem enter second ge...   
4  want talk background idea car art actually mea...   

                                         squash_tags  
0  alternative energy,culture,politics,science,cl...  
1  industrial design,alternative energy,invention...  
2  poverty,economics,investment,culture,politics,...  
3  industrial design,invention,engineering,entrep...  
4  industrial design,transportation,invention,des...

In [4]:
df_x = df[['headline', 'clean_transcript_string']]
df_y = df[['squash_tags']]

In [5]:
from sklearn.preprocessing import MultiLabelBinarizer

y = []
for index, row in df_y.iterrows():
    y.append(set(row['squash_tags'].split(',')))
    
mlb = MultiLabelBinarizer()
encoded_y = mlb.fit_transform(y)

In [6]:
print(encoded_y[0])
print(len(encoded_y[0]))
print(encoded_y[53])
print(mlb.inverse_transform(encoded_y))

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
179
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[('alternative energy', 'climate change', 'culture', 'environment', 'global issues', 'politics', 'science', 'sustainability', 'technology'), ('alternative energy', 'design', 'engineering', 'global issues', 'industrial design', 'invention'), ('business', 'culture', 'ec

In [7]:

from gensim import utils
import gensim.parsing.preprocessing as gsp

filters = [
           gsp.strip_tags, 
           gsp.strip_punctuation,
           gsp.strip_multiple_whitespaces,
           gsp.strip_numeric,
           gsp.remove_stopwords, 
           gsp.strip_short, 
           gsp.stem_text
          ]

def clean_text(s):
    s = s.lower()
    s = utils.to_unicode(s)
    for f in filters:
        s = f(s)
    return s

In [8]:

from gensim.models.doc2vec import TaggedDocument, Doc2Vec
from sklearn.base import BaseEstimator
from sklearn import utils as skl_utils
from tqdm import tqdm

import multiprocessing
import numpy as np

class Doc2VecTransformer(BaseEstimator):

    def __init__(self, vector_size=100, learning_rate=0.02, epochs=20, field=None):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self._model = None
        self.vector_size = vector_size
        self.workers = multiprocessing.cpu_count() - 1
        self.field = field

    def fit(self, df_x, df_y=None):
        tagged_x = [TaggedDocument(clean_text(row[str(self.field)]).split(), [index]) for index, row in df_x.iterrows()]
        model = Doc2Vec(documents=tagged_x, vector_size=self.vector_size, workers=self.workers)

        for epoch in range(self.epochs):
            model.train(skl_utils.shuffle([x for x in tqdm(tagged_x)]), total_examples=len(tagged_x), epochs=1)
            model.alpha -= self.learning_rate
            model.min_alpha = model.alpha

        self._model = model
        return self

    def transform(self, df_x):
        return np.asmatrix(np.array([self._model.infer_vector(clean_text(row[str(self.field)]).split())
                                     for index, row in df_x.iterrows()]))

In [9]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(df_x, encoded_y)

In [10]:
print(test_x)

                                           headline  \
396                           How to grow fresh air   
2094     We can reprogram life. How to do it wisely   
67                           Technology's long tail   
2267         The ethical dilemma of designer babies   
257   Let's look for life in the outer solar system   
...                                             ...   
154                                  My magic moves   
1334          Could the sun be good for your heart?   
1652                    Color blind or color brave?   
1029                            Don't regret regret   
2187             The deadly legacy of cluster bombs   

                                clean_transcript_string  
396   year ago allergic delhi air doctor tell lung c...  
2094  actor call dustin hoffman year ago movie hear ...  
67    like speak technology trend follow follow rela...  
2267  designer baby parenttobe scientist decide road...  
257   remember year happen live little town princ

In [11]:

from sklearn.pipeline import FeatureUnion

fu = FeatureUnion(transformer_list=[('title_doc2vec',Doc2VecTransformer(field='headline')),
                                    ('body_doc2vec',Doc2VecTransformer(field='clean_transcript_string'))])

In [12]:
from sklearn.pipeline import Pipeline
from skmultilearn.problem_transform import BinaryRelevance
from sklearn.ensemble import RandomForestClassifier

binary_rel_model = BinaryRelevance(RandomForestClassifier(n_jobs=-1, n_estimators=10))
multi_label_rf_br_model = Pipeline(steps=[
                           ('feature_union', fu),
                           ('binary_relevance', binary_rel_model)
                        ])

In [13]:

import sklearn.metrics as metrics

def hamming_loss(multi_label_model_pipeline,train_x, train_y, test_x, test_y):
    predictions_test_y = multi_label_model_pipeline.predict(test_x)
    return metrics.hamming_loss(y_true=test_y, y_pred=predictions_test_y)

In [14]:
multi_label_rf_br_model.fit(train_x, train_y)
print('Hamming loss for test data :', hamming_loss(multi_label_rf_br_model,train_x,train_y,test_x,test_y))

100%|████████████████████████████████████| 1789/1789 [00:00<00:00, 897453.64it/s]


Hamming loss for test data : 0.03762761666807033


In [15]:
predictions_test_y = multi_label_rf_br_model.predict(test_x)
print(predictions_test_y.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [16]:
# print(predictions_test_y.toarray()[-3])
# print(encoded_y[154])
# print(mlb.inverse_transform(predictions_test_y.toarray()))
print(test_y[27])
'''
103  want year opportunity close conference incredi...  
31   think podium bite scar chris ask tell structur...  
41   music music end end hi sirena year old connect...  
93   thank get story arrive plane long journey west...  
152  go try view world problem opportunity face ask...  
2    public dewey long ago observe constitute discu...  
154                                              music  
124  consider storyteller tell story usual way sens...  
94 
'''

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[(), (), (), ('design',), ('science',), ('science',), (), (), (), (), (), (), ('innovation',), (), (), ('design',), (), (), (), (), (), (), (), (), ('design',), ('animals', 'design', 'technology'), ('business', 'collaboration', 'community', 'culture', 'film', 'language', 

'\n103  want year opportunity close conference incredi...  \n31   think podium bite scar chris ask tell structur...  \n41   music music end end hi sirena year old connect...  \n93   thank get story arrive plane long journey west...  \n152  go try view world problem opportunity face ask...  \n2    public dewey long ago observe constitute discu...  \n154                                              music  \n124  consider storyteller tell story usual way sens...  \n94 \n'

In [33]:
print(test_y[-5])
print(mlb.inverse_transform(test_y)[-5])
pd.concat(pd.Series(mlb.inverse_transform(test_y)), pd.Series(test_y),axis=1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
('culture', 'entertainment', 'performance')


Exception: Data must be 1-dimensional